version: "3.9"

services:
  greeter-service:
    build:
      context: .
      dockerfile: greeter.Dockerfile
    ports:
      - "8080:8080"
  user-service:
    build:
      context: .
      dockerfile: user.Dockerfile
    ports:
      - "8081:8081"
